#!/bin/bash

echo "=== Manual Image Copy Script ==="
echo "Please run these commands manually in Terminal:"
echo ""
echo "1. Navigate to source directory:"
echo "   cd '/Users/mcapace/Desktop/bib-tucker-campaign/images'"
echo ""
echo "2. Copy all images:"
echo "   cp *.png '/Users/mcapace/Desktop/deutsch-bibb-tucker/public/images/'"
echo "   cp *.jpg '/Users/mcapace/Desktop/deutsch-bibb-tucker/public/images/'"
echo ""
echo "3. Verify images were copied:"
echo "   ls -la '/Users/mcapace/Desktop/deutsch-bibb-tucker/public/images/'"
echo ""
echo "4. Commit the changes:"
echo "   cd '/Users/mcapace/Desktop/deutsch-bibb-tucker'"
echo "   git add ."
echo "   git commit -m 'Add campaign images'"
echo "   git push origin main"
echo ""
echo "=== Alternative: Use Finder ==="
echo "1. Open Finder"
echo "2. Go to: /Users/mcapace/Desktop/bib-tucker-campaign/images/"
echo "3. Select all files (Cmd+A)"
echo "4. Copy (Cmd+C)"
echo "5. Go to: /Users/mcapace/Desktop/deutsch-bibb-tucker/public/images/"
echo "6. Paste (Cmd+V)"
echo ""
echo "=== Essential Images ==="
echo "- bib-tucker-logo.png"
echo "- whisky-advocate-logo.png"
echo "- gold-roast-bottle.jpg"
echo "- double-char-bottle.jpg"
echo "- classic-six-bottle.jpg"
